In [1]:
import sys
from pathlib import Path

# 1. Определяем корень проекта
# (подбираем количество .parent, чтобы попасть в max_projects)
project_root = Path.cwd().parent

# 2. Добавляем корень в пути поиска модулей
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# 3. Проверяем, что путь добавлен
print(f"✅ Project root: {project_root}")
print(f"✅ Sys path: {sys.path[:3]}...")

✅ Project root: c:\Users\123\Desktop\start_vector
✅ Sys path: ['c:\\Users\\123\\Desktop\\start_vector', 'C:\\Python314\\python314.zip', 'C:\\Python314\\DLLs']...

In [2]:
import logging
import pandas as pd
from src_oop.jobs.orders_articles_analyze.repository import ArticleAnalyzeRepository

In [3]:
repo = ArticleAnalyzeRepository()
df_gen = repo.get_general_stat(28, 1)
df_adv = repo.get_adv_stat(28, 1)
df_all_goods = repo.get_all_goods_directory()

In [4]:
df = pd.merge(df_gen, df_adv, on=["article_id", "date"], how="outer")

In [7]:
df[df['article_id'] == 362376273].sort_values('date', ascending=False).head()

,date,week_num,month_num,account,local_vendor_code,article_id,subject_name,price_with_disc,spp,orders_sum_rub,...,returns_count_rep,cost_price_sales_fin_rep,cost_price_returns_fin_rep,clicks,views,ctr,cpc,cpm,adv_spend,bonuses
44876,2026-03-26,13.0,3.0,ОГАНЕСЯН,wild1519,362376273,Казаны,0.0,NaN,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44875,2026-03-25,NaN,NaN,NaN,NaN,362376273,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,340.0,NaN,NaN
44874,2026-03-23,NaN,NaN,NaN,NaN,362376273,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,2.0,0.0,0.0,395.0,NaN,NaN
44873,2026-03-19,12.0,3.0,ОГАНЕСЯН,wild1519,362376273,Казаны,0.0,NaN,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44872,2026-03-18,12.0,3.0,ОГАНЕСЯН,wild1519,362376273,Казаны,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,500.0,NaN,NaN

In [7]:
# === Обработка пропусков в данных ===
# Обрабатываем пропуски в датах
df['date'] = pd.to_datetime(df['date'])
df['week_num'] = df['date'].dt.isocalendar().week
df['month_num'] = df['date'].dt.month

In [8]:
# === Обрабатываем пропуски в данных по товарам ===
# Создам набор данных по товарам из df_gen, чтобы заполнить пропуски в df
df_goods = df_gen[['account', 'local_vendor_code', 'article_id', 'subject_name']].drop_duplicates(subset=['article_id'])

# Заполняем каждую колонку отдельно через map
cols_to_fill = ['account', 'local_vendor_code', 'subject_name']

for col in cols_to_fill:
    # Создаем "словарь" {article_id: значение_колонки}
    mapping_dict = df_goods.set_index('article_id')[col]
    
    # Заполняем пропуски в основном df
    df[col] = df[col].fillna(df['article_id'].map(mapping_dict))

In [6]:
df[df['article_id'] == 362376273].sort_values('date', ascending=False).head()

,date,week_num,month_num,account,local_vendor_code,article_id,subject_name,price_with_disc,spp,orders_sum_rub,...,returns_count_rep,cost_price_sales_fin_rep,cost_price_returns_fin_rep,clicks,views,ctr,cpc,cpm,adv_spend,bonuses
44876,2026-03-26,13.0,3.0,ОГАНЕСЯН,wild1519,362376273,Казаны,0.0,NaN,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44875,2026-03-25,NaN,NaN,NaN,NaN,362376273,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,340.0,NaN,NaN
44874,2026-03-23,NaN,NaN,NaN,NaN,362376273,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,2.0,0.0,0.0,395.0,NaN,NaN
44873,2026-03-19,12.0,3.0,ОГАНЕСЯН,wild1519,362376273,Казаны,0.0,NaN,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44872,2026-03-18,12.0,3.0,ОГАНЕСЯН,wild1519,362376273,Казаны,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,500.0,NaN,NaN