In [2]:
import sys
from pathlib import Path

# 1. Определяем корень проекта
# (подбираем количество .parent, чтобы попасть в max_projects)
project_root = Path.cwd().parent

# 2. Добавляем корень в пути поиска модулей
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# 3. Проверяем, что путь добавлен
print(f"✅ Project root: {project_root}")
print(f"✅ Sys path: {sys.path[:3]}...")

✅ Project root: c:\Users\123\Desktop\start_vector
✅ Sys path: ['c:\\Users\\123\\Desktop\\start_vector', 'C:\\Python314\\python314.zip', 'C:\\Python314\\DLLs']...

In [3]:
import logging
import pandas as pd
from src_oop.jobs.orders_articles_analyze.repository import ArticleAnalyzeRepository

In [4]:
repo = ArticleAnalyzeRepository()
df_gen = repo.get_general_stat()
df_adv = repo.get_adv_stat()

In [5]:
df = pd.merge(df_gen, df_adv, on=["article_id", "date"], how="outer")

In [8]:
df[df['article_id'] == 559034754].sort_values('date', ascending=False).head()

,date,week_num,month_num,account,local_vendor_code,article_id,subject_name,price_with_disc,spp,orders_sum_rub,...,returns_count_rep,cost_price_sales_fin_rep,cost_price_returns_fin_rep,clicks,views,ctr,cpc,cpm,adv_spend,bonuses
78483,2026-03-19,NaN,NaN,NaN,NaN,559034754,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,210.0,NaN,NaN
78482,2026-03-17,NaN,NaN,NaN,NaN,559034754,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,150.0,NaN,NaN
78481,2026-03-15,11.0,3.0,ТОНОЯН,wild1776,559034754,Швабры,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,270.0,NaN,NaN
78480,2026-03-14,11.0,3.0,ТОНОЯН,wild1776,559034754,Швабры,0.0,NaN,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78479,2026-03-13,11.0,3.0,ТОНОЯН,wild1776,559034754,Швабры,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,210.0,NaN,NaN

In [ ]:
# === Обработка пропусков в данных ===
# Обрабатываем пропуски в датах
df['date'] = pd.to_datetime(df['date'])
df['week_num'] = df['date'].dt.isocalendar().week
df['month_num'] = df['date'].dt.month
# Обрабатываем пропуски в данных по товарам
# Создам набор данных по товарам из df_gen, чтобы заполнить пропуски в df
df_goods = df_gen[['account', 'local_vendor_code', 'aricle_id', 'subject_name']].drop_duplicates()
df = pd.merge(df, df_goods, on=['account', 'local_vendor_code', 'aricle_id'], how='left', suffixes=('_gen', '_goods'))
df = df.drop(coc)

df[df['article_id'] == 559034754].sort_values('date', ascending=False).head()

,date,week_num,month_num,account,local_vendor_code,article_id,subject_name,price_with_disc,spp,orders_sum_rub,...,returns_count_rep,cost_price_sales_fin_rep,cost_price_returns_fin_rep,clicks,views,ctr,cpc,cpm,adv_spend,bonuses
78483,2026-03-19,12,3,NaN,NaN,559034754,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,210.0,NaN,NaN
78482,2026-03-17,12,3,NaN,NaN,559034754,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,150.0,NaN,NaN
78481,2026-03-15,11,3,ТОНОЯН,wild1776,559034754,Швабры,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,270.0,NaN,NaN
78480,2026-03-14,11,3,ТОНОЯН,wild1776,559034754,Швабры,0.0,NaN,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78479,2026-03-13,11,3,ТОНОЯН,wild1776,559034754,Швабры,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,210.0,NaN,NaN

In [18]:
df.shape

(391537, 60)